trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    containerRegistry: 'Prague'
    repository: 'fhl2020Gateway'
    command: 'buildAndPush'
    Dockerfile: '**/server/gateway/Dockerfile'