version: '3'
services:
    mongodb:
        image: mongo:3.4.3
    redis:
        image: redis:alpine
    gateway:
        image: gateway_gateway:latest
        ports:
            - "8800:8800"
            - "5888:5858"
        command: node --inspect=0.0.0.0:5858 dist/www.js
        environment:
            - DEBUG=fluid:*
            - NODE_ENV=development
        restart: always